from __future__ import unicode_literals
from logistics_project.apps.malawi.tests.approval import *
from logistics_project.apps.malawi.tests.boot import *
from logistics_project.apps.malawi.tests.createuser import *
from logistics_project.apps.malawi.tests.nag import *
from logistics_project.apps.malawi.tests.product import *
from logistics_project.apps.malawi.tests.receipts import *
from logistics_project.apps.malawi.tests.register import *
from logistics_project.apps.malawi.tests.report import *
from logistics_project.apps.malawi.tests.roles import *
from logistics_project.apps.malawi.tests.stockonhand import *
from logistics_project.apps.malawi.tests.transfer import *
from logistics_project.apps.malawi.tests.warehouse.consumption import *
