from django.conf.urls import *
from . import views
from .warehouse import views as warehouse_views
from logistics import views as logistics_views

reportpatterns = [
    url(r'^home/$', warehouse_views.default_landing, name='malawi_dashboard'),
    url(r'^r/home/$', warehouse_views.home, name='malawi_hsa_dashboard'),
    url(r'^r/(?P<slug>[\w\s-]+)/$', warehouse_views.get_report, name=''),
    url(r'^f/home/$', warehouse_views.facility_home, name='malawi_facility_dashboard'),
    url(r'^f/(?P<slug>[\w\s-]+)/$', warehouse_views.get_facility_report, name=''),
]


urlpatterns = [
    url(r'^set_dashboard/$',
        views.set_current_dashboard,
        name="set_current_dashboard"),
    url(r'^management/$',
        views.organizations,
        name="malawi_management"),
    url(r'^management/organizations/$',
        views.organizations,
        name="malawi_organizations"),
    url(r'^management/organizations/new/$',
        views.new_organization,
        name="malawi_new_organization"),
    url(r'^management/organizations/edit/(?P<pk>\d+)/$',
        views.edit_organization,
        name="malawi_edit_organization"),
    url(r'^management/contacts/$',
        views.contacts,
        name="malawi_contacts"),
    url(r'^management/accounts/new/$',
        views.create_account,
        name="malawi_new_account"),
    url(r'^management/permissions/$',
        views.permissions,
        name="malawi_permissions"),
    url(r'^management/permissions/edit/(?P<pk>\d+)/$',
        views.edit_permission,
        name="malawi_edit_permissions"),
    url(r'^management/places/$',
        views.places,
        name="malawi_places"),
    url(r'^management/products/$',
        views.products,
        name="malawi_products"),
    url(r'^management/products/new/$',
        views.add_product,
        name="malawi_product_new"),
    url(r'^management/products/(?P<pk>\d+)/$',
        views.single_product,
        name="malawi_single_product"),
    url(r'^management/products/(?P<pk>\d+)/deactivate/$',
        views.deactivate_product_view,
        name="malawi_deactivate_product"),
    url(r'^management/sms-tracking/$',
        views.sms_tracking,
        name="malawi_sms_tracking"),
    url(r'^management/telco-tracking/$',
        views.telco_tracking,
        name="malawi_telco_tracking"),
    
    url(r'^management/hsas/$',
        views.manage_hsas,
        name='malawi_manage_hsas'),
    url(r'^management/hsas/(?P<pk>\d+)/$',
        views.manage_hsa,
        name='malawi_manage_hsa'),
    url(r'^management/hsas/(?P<pk>\d+)/deactivate/$',
        views.deactivate_hsa,
        name='malawi_manage_deactivate_hsa'),
    url(r'^management/facilities/$',
        views.manage_facilities,
        name='malawi_manage_facilities'),
    url(r'^management/download_facilities/$',
        views.download_facilities,
        name='download_facilities'),
    url(r'^management/upload_facilities/$',
        views.upload_facilities,
        name='upload_facilities'),
    url(r'^management/outreach/$',
        views.outreach,
        name='malawi_manage_outreach'),
    url(r'^management/outreach/send/$',
        views.send_outreach,
        name='malawi_manage_outreach_send'),

    url(r'^hsas/$',
        views.hsas,
        name="malawi_hsas"),
    url(r'^hsa/(?P<code>\d+)/$',
        views.hsa,
        name="malawi_hsa"),
    url(r'^deactivate/(?P<pk>\d+)/$',
         views.deactivate_hsa,
        name="deactivate_hsa"),
     url(r'^reactivate/(?P<code>\d+)/(?P<name>.+)/$',
         views.reactivate_hsa,
        name="reactivate_hsa"),
    url(r'^help/$',
        views.help,
        name="malawi_help"),
    url(r'^status/$',
        views.status,
        name="malawi_status"),
    url(r'^is-kannel-up/$',
        views.is_kannel_up,
        name="malawi_kannel_up"),
    url(r'^airtel-users/$',
        views.airtel_numbers,
        name="malawi_airtel"),
    url(r'^register-hsa/$',
        views.register_user,
        name="malawi_hsa"),
    url(r'^monitoring/$',
        views.monitoring,
        name="malawi_monitoring"),
    url("^monitoring/(?P<report_slug>[\w_]+)/$",
        views.monitoring_report,
        name="malawi_monitoring_report"),
    url(r'^export_amc/$',
        views.export_amc_csv,
        name="export_amc_csv"),
    url(r'^global_stats/$',
        logistics_views.global_stats,
        name="global_stats"),
    url(r'^500/?$', views.raise_500, name='raise_500'),
] + reportpatterns
