# Generated by Django 3.2.12 on 2022-05-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelog', '0002_alter_message_direction'),
        ('logistics', '0004_auto_20220505_1519'),
        ('rapidsms', '0003_auto_20220308_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_message',
            field=models.ForeignKey(blank=True, help_text="The contact's last inbound message", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_last_message', to='messagelog.message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='commodities',
            field=models.ManyToManyField(blank=True, help_text='User manages these commodities.', related_name='reported_by', to='logistics.Product'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, help_text='The language which this contact prefers to communicate in, as a W3C language tag. If this field is left blank, RapidSMS will default to: en-us', max_length=6),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='number',
            field=models.CharField(help_text='Destination telephone number', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='report',
            field=models.CharField(help_text='Actual report text', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='report_id',
            field=models.CharField(help_text='Gateway assigned ID', max_length=255),
        ),
    ]
