from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('',
    url(r'^dashboard/$', 'logistics_project.apps.tanzania.views.dashboard', name="tz_dashboard"),
    url('^facilities/index/$', 'logistics_project.apps.tanzania.views.facilities_index', name="facilities_index"),
    url(r'^facilities/(?P<facility_id>\d+)/message_history/$', 'logistics_project.apps.tanzania.views.facility_messages', name="facility_messages"),
    url('^facility/(?P<facility_id>\d+)/$', 'logistics_project.apps.tanzania.views.facility_details', name="tz_facility_details"),
    url(r'^supervision/$', 'logistics_project.apps.tanzania.views.supervision', name='supervision'),
    url(r'^training/$', 'logistics_project.apps.tanzania.views.training', name='training'),
    url(r'^training/download_facilities/$', 'logistics_project.apps.tanzania.views.download_facilities', 
        name='download_facilities'),
    url(r'^training/upload_facilities/$', 'logistics_project.apps.tanzania.views.upload_facilities', 
        name='upload_facilities'),
    url(r'^reports/(?P<slug>\w+)/$', 'logistics_project.apps.tanzania.views.reports_shared', name='new_reports'),
    url(r'^export_report/(?P<slug>\w+)/$', 'logistics_project.apps.tanzania.views.export_report', name='export_report'),
    url(r'^reports/$', 'logistics_project.apps.tanzania.views.reports_shared', name='new_reports'),
    url(r'^docdownload/(?P<facility_id>\w+)/$', 'logistics_project.apps.tanzania.views.docdownload', name="tz_docdownload"),
    url(r'^change_language/$', 'logistics_project.apps.tanzania.views.change_language', name="tz_language"),
    url(r'^change_language/post/$', 'logistics_project.apps.tanzania.views.change_language_real', name="tz_language_redirect"),
    url(r'^schedule/$', direct_to_template, {'template': 'tanzania/sms_schedule.html'}, name="tz_sms_schedule"),
    url(r'^download_supervision_document/(?P<document_id>\w+)/$', 'logistics_project.apps.tanzania.views.download_supervision_doc', name='download_supervision_doc'),
    url(r'^delete_supervision_document/(?P<document_id>\w+)/$', 'logistics_project.apps.tanzania.views.delete_supervision_doc', name='delete_supervision_doc'),
    url(r'^sms_broadcast/$', 'logistics_project.apps.tanzania.views.sms_broadcast', name='sms_broadcast'),
    url(r'^facilities_by_district/$', 'logistics_project.apps.tanzania.views.facilities_by_district', name='facilities_by_district'),
    url(r'^alerts/$', 'logistics_project.apps.tanzania.views.alerts', name='tz_alerts'),
)
