# Generated by Django 3.2.12 on 2022-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20220308_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsprofile',
            name='current_dashboard_base_level',
            field=models.CharField(default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='base_level',
            field=models.CharField(default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='response_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('stocked_out', 'stocked_out'), ('partially_stocked', 'partially_stocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('stocked_out', 'stocked_out'), ('partially_stocked', 'partially_stocked'), ('received', 'received'), ('canceled', 'canceled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('confirmed', 'confirmed'), ('canceled', 'canceled')], max_length=10),
        ),
    ]
